import { expect, test } from "@playwright/test";
import { PDFDocument } from "pdf-lib";
import { writeFile } from "node:fs/promises";

test("four roles: accounts → two rooms → form/PDF → rework → quantities/covers → print completion", async ({ page }, info) => {
  test.skip(!process.env.REVIEW_PASSWORD || info.project.name !== "chromium", "Requires isolated local workflow test accounts");
  test.setTimeout(300_000);
  const suffix = Date.now().toString().slice(-8);
  const course = `WF${suffix}`, round = `Workflow ${suffix}`, teacher = `teacher.${suffix}`;
  const teacherName = `อาจารย์ทดสอบ ${suffix}`, temporary = "InitialWorkflow2026!", personal = "PersonalWorkflow2026!";
  const browserErrors: string[] = [];
  page.on("pageerror", error => browserErrors.push(error.message));
  page.on("dialog", async dialog => { browserErrors.push("native dialog"); await dialog.dismiss(); });
  const logout = async () => {
    await page.getByRole("button", { name: "ออกจากระบบ", exact: true }).first().click();
    // Wait for sign-out and navigation before opening another account's login page.
    await expect(page).toHaveURL(/\/login$/);
  };
  const login = async (username: string, password = process.env.REVIEW_PASSWORD!, initial = false) => {
    await page.goto("/login");
    await page.getByLabel("Username", { exact: true }).fill(username);
    await page.getByLabel("รหัสผ่าน", { exact: true }).fill(password);
    for (let attempt = 0; attempt < 3; attempt++) {
      const response = page.waitForResponse(r => r.url().includes("/sign-in/username"));
      await page.getByRole("button", { name: "เข้าสู่ระบบ", exact: true }).click();
      if ((await response).status() !== 429) break;
      await page.waitForTimeout(11_000);
    }
    await expect(page).toHaveURL(initial ? /change-password/ : /\/dashboard$/);
  };
  const choose = async (name: string, option: string | RegExp) => {
    await page.getByRole("combobox", { name, exact: true }).click();
    await page.getByRole("option", { name: option, exact: typeof option === "string" }).click();
  };
  await login("review.admin");
  await page.goto("/dashboard/users");
  await page.getByLabel("Username", { exact: true }).fill(teacher);
  await page.getByLabel("ชื่อ-นามสกุล", { exact: true }).first().fill(teacherName);
  await page.getByLabel("อีเมล", { exact: true }).first().fill(`${teacher}@example.local`);
  await choose("บทบาท", "อาจารย์");
  await page.getByLabel("รหัสผ่านชั่วคราว", { exact: true }).fill(temporary);
  await page.getByRole("button", { name: "สร้างบัญชี", exact: true }).click();
  await expect(page.getByRole("cell").filter({ hasText: teacher }).first()).toBeVisible();
  await logout();
  await login("review.officer");
  await page.goto("/dashboard/rounds");
  await choose("รอบสอบ", "รอบสอบอื่น");
  await page.getByLabel("ชื่อรอบสอบอื่น", { exact: true }).fill(round);
  await page.getByLabel("ปีการศึกษา").fill("2569"); await page.getByLabel("ภาคการศึกษา").fill("1");
  await page.getByRole("button", { name: "สร้างรอบสอบ", exact: true }).click();
  await expect(page.getByText("สร้างรอบสอบแล้ว", { exact: true })).toBeVisible();
  for (const room of ["A", "B"]) {
    await page.goto("/dashboard/rooms");
    await page.getByLabel("รหัสห้อง").fill(course + room);
    await page.getByLabel("ชื่อห้อง", { exact: true }).fill(`ห้องทดสอบ ${room}`);
    await page.getByLabel("ความจุ", { exact: true }).fill("50");
    await page.getByRole("button", { name: "เพิ่มห้องสอบ", exact: true }).click();
    await expect(page.getByRole("cell", { name: course + room, exact: true })).toBeVisible();
  }
  const roomRow = page.getByRole("row").filter({ has: page.getByRole("cell", { name: course + "A", exact: true }) });
  await roomRow.getByRole("link", { name: "แก้ไขห้อง", exact: true }).click();
  await expect(page.getByRole("heading", { name: "แก้ไขห้องสอบ", exact: true })).toBeVisible();
  await expect(page.getByLabel("ชื่อห้อง", { exact: true })).toHaveValue("ห้องทดสอบ A");
  await page.getByLabel("อาคาร", { exact: true }).fill("อาคารทดสอบ");
  await page.getByRole("button", { name: "บันทึกแก้ไขห้องสอบ", exact: true }).click();
  await expect(roomRow).toContainText("อาคารทดสอบ");
  await page.goto("/dashboard/rooms");
  await page.getByLabel("รหัสห้อง").fill(course + "DELETE");
  await page.getByLabel("ชื่อห้อง", { exact: true }).fill("ห้องทดสอบลบ");
  await page.getByLabel("ความจุ", { exact: true }).fill("10");
  await page.getByRole("button", { name: "เพิ่มห้องสอบ", exact: true }).click();
  const unusedRoom = page.getByRole("row").filter({ hasText: course + "DELETE" });
  await unusedRoom.getByRole("button", { name: "ลบ", exact: true }).click();
  await page.getByRole("button", { name: "ยืนยันลบ", exact: true }).click();
  await expect(unusedRoom).toHaveCount(0);
  await page.goto("/dashboard/subjects");
  await choose("รอบสอบ", new RegExp(round)); await choose("อาจารย์ผู้รับผิดชอบ", new RegExp(teacher));
  await page.getByLabel("รหัสวิชา", { exact: true }).fill(course);
  await page.getByLabel("ชื่อวิชา", { exact: true }).fill("การเขียนโปรแกรมและการจัดพิมพ์ข้อสอบสำหรับรายวิชาที่มีชื่อยาว");
  await page.getByRole("combobox", { name: "คณะ", exact: true }).click();
  await expect(page.getByRole("option")).toHaveCount(16);
  await page.getByRole("option", { name: "คณะวิศวกรรมศาสตร์", exact: true }).click();
  await page.getByLabel("กลุ่มเรียน").fill("1");
  await page.getByRole("button", { name: "เพิ่มรายวิชา", exact: true }).click();
  await expect(page.getByText("เพิ่มรายวิชาแล้ว", { exact: true })).toBeVisible();
  await page.getByRole("row").filter({ hasText: course }).getByRole("link", { name: "แก้ไขรายวิชา", exact: true }).click();
  await expect(page.getByRole("heading", { name: "แก้ไขรายวิชา", exact: true })).toBeVisible();
  await expect(page.getByRole("combobox", { name: "คณะ", exact: true })).toContainText("คณะวิศวกรรมศาสตร์");
  await page.getByLabel("กลุ่มเรียน").fill("2");
  await page.getByRole("button", { name: "บันทึกแก้ไขรายวิชา", exact: true }).click();
  await expect(page.getByRole("row").filter({ hasText: course }).getByRole("cell", { name: "2", exact: true })).toBeVisible();
  for (const room of ["A", "B"]) {
    await page.goto("/dashboard/subjects");
    await choose("รายวิชา", new RegExp(course)); await choose("ห้องสอบ", new RegExp(course + room));
    await page.getByLabel("วันที่สอบ").fill("2026-09-20");
    await page.getByLabel("เริ่ม", { exact: true }).fill("09:00"); await page.getByLabel("สิ้นสุด", { exact: true }).fill("11:00");
    await expect(page.getByLabel("ผู้เข้าสอบห้องนี้")).toHaveCount(0);
    await page.getByRole("button", { name: "บันทึกตารางสอบ", exact: true }).click();
    await expect(page.getByText("บันทึกตารางสอบแล้ว", { exact: true })).toBeVisible();
  }
  const scheduleRow = page.getByRole("row").filter({ hasText: course + "B" });
  await scheduleRow.getByRole("link", { name: "แก้ไขตาราง", exact: true }).click();
  await expect(page.getByRole("heading", { name: "แก้ไขตารางสอบ", exact: true })).toBeVisible();
  await page.getByLabel("สิ้นสุด", { exact: true }).fill("12:00");
  await page.getByRole("button", { name: "บันทึกตารางสอบ", exact: true }).click();
  await expect(scheduleRow).toContainText("12:00");
  await scheduleRow.getByRole("button", { name: "ลบ", exact: true }).click();
  await page.getByRole("button", { name: "ยืนยันลบ", exact: true }).click();
  await expect(scheduleRow).toHaveCount(0);
  await page.goto("/dashboard/subjects");
  await choose("รายวิชา", new RegExp(course)); await choose("ห้องสอบ", new RegExp(course + "B"));
  await page.getByLabel("วันที่สอบ").fill("2026-09-20");
  await page.getByLabel("เริ่ม", { exact: true }).fill("09:00"); await page.getByLabel("สิ้นสุด", { exact: true }).fill("11:00");
  await page.getByRole("button", { name: "บันทึกตารางสอบ", exact: true }).click();
  await expect(page.getByText("บันทึกตารางสอบแล้ว", { exact: true })).toBeVisible();
  await logout(); await login(teacher, temporary, true);
  await page.getByLabel("รหัสผ่านชั่วคราว", { exact: true }).fill(temporary);
  await page.getByLabel("รหัสผ่านใหม่", { exact: true }).fill(personal);
  await page.getByLabel("ยืนยันรหัสผ่านใหม่", { exact: true }).fill(personal);
  await page.getByRole("button", { name: "บันทึกรหัสผ่านใหม่", exact: true }).click();
  await expect(page).toHaveURL(/\/dashboard$/);
  await page.goto("/dashboard/requests/new");
  await choose("รายวิชาของคุณ", new RegExp(course));
  await page.getByRole("button", { name: "ถัดไป: กรอกแบบฟอร์ม", exact: true }).click();
  await page.getByLabel("สาขาวิชา", { exact: true }).fill("วิทยาการคอมพิวเตอร์");
  await choose("ภาษาข้อสอบ", "ไทย"); await choose("รูปแบบพิมพ์", "สองหน้า");
  await choose("กระดาษคำตอบคอมพิวเตอร์", "ไม่ต้องการ"); await choose("ประเภทการสอบ", "ในตาราง");
  await page.getByLabel("เบอร์ผู้ประสานงาน").fill("0812345678");
  await page.getByRole("checkbox", { name: "นำเครื่องคิดเลขเข้าห้องสอบได้", exact: true }).check();
  await page.getByLabel("คำอธิบายเพิ่มเติมผู้ส่งข้อสอบ").fill("ตรวจจำนวนข้อสอบให้ครบก่อนเริ่มสอบ และแจ้งผู้คุมสอบเมื่อพบข้อผิดพลาด");
  await page.getByLabel("จำนวนชุดข้อสอบที่ขอ", { exact: true }).nth(0).fill("10001");
  await expect(page.getByRole("alert").filter({ hasText: "ห้องนี้รองรับ 50 คน" })).toBeVisible();
  await page.getByRole("button", { name: "บันทึกฉบับร่าง", exact: true }).click();
  await expect(page.getByText("กรุณาแก้ไขจำนวนในช่องที่มีข้อความเตือนด้านล่าง", { exact: true })).toBeVisible();
  await expect(page.getByLabel("สาขาวิชา", { exact: true })).toHaveValue("วิทยาการคอมพิวเตอร์");
  await expect(page.getByText(/too_big|expected number|"origin"/)).toHaveCount(0);
  await page.getByLabel("จำนวนชุดข้อสอบที่ขอ", { exact: true }).nth(0).fill("50");
  await page.getByLabel("จำนวนชุดข้อสอบที่ขอ", { exact: true }).nth(1).fill("30");
  const pdf = await PDFDocument.create(); pdf.addPage().drawText("Workflow fixture - not a real examination");
  const buffer = Buffer.from(await pdf.save());
  await page.getByLabel("ไฟล์ข้อสอบ PDF (สูงสุด 100 MB)", { exact: true }).setInputFiles({ name: "workflow-v1.pdf", mimeType: "application/pdf", buffer });
  for (const width of [360, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 1000 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
    await page.screenshot({ path: info.outputPath(`teacher-form-${width}.png`), fullPage: true });
  }
  await page.getByRole("button", { name: "ถัดไป: ตรวจทาน", exact: true }).click();
  await expect(page.getByRole("button", { name: "ยืนยันส่งข้อสอบให้หน่วยโสต" })).toBeVisible({ timeout: 30_000 });
  await page.getByRole("button", { name: "ยืนยันส่งข้อสอบให้หน่วยโสต" }).click();
  await expect(page).toHaveURL(/\/requests\/[a-f0-9-]+$/);
  const requestUrl = page.url();
  await logout(); await login("review.print"); await page.goto(requestUrl);
  const fileLink = page.getByTestId("current-task").getByRole("link", { name: /workflow-v1.pdf/ });
  const fileResponse = await page.request.get((await fileLink.getAttribute("href"))!);
  expect(fileResponse.ok()).toBe(true);
  await page.getByText("ต้องการส่งกลับให้อาจารย์แก้ไข", { exact: true }).click();
  await page.getByLabel("เหตุผลที่ส่งกลับ").fill("กรุณาตรวจข้อความคำแนะนำอีกครั้ง");
  await page.getByRole("button", { name: "ส่งกลับให้อาจารย์แก้ไข" }).click();
  await expect(page.getByText("ปฏิเสธ/ส่งกลับแก้ไข", { exact: true }).first()).toBeVisible();
  await logout(); await login(teacher, personal); await page.goto(requestUrl);
  await expect(page.getByLabel("ไฟล์ข้อสอบ PDF (สูงสุด 100 MB)", { exact: true })).toBeEnabled();
  await page.getByLabel("ไฟล์ข้อสอบ PDF (สูงสุด 100 MB)", { exact: true }).setInputFiles({ name: "workflow-v2.pdf", mimeType: "application/pdf", buffer });
  await expect(page.getByText("ไฟล์ที่เลือก: workflow-v2.pdf", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "ถัดไป: ตรวจทาน", exact: true }).click();
  await expect(page.getByText(/ข้อสอบ .*workflow-v2\.pdf/)).toBeVisible({ timeout: 30_000 });
  await page.getByRole("button", { name: "ยืนยันส่งข้อสอบให้หน่วยโสต" }).click();
  // The submit button changes to a pending label immediately; wait for actual completion.
  await expect(page.getByRole("button", { name: "กำลังส่ง...", exact: true })).toHaveCount(0, { timeout: 45_000 });
  await expect(page.getByRole("button", { name: "ยืนยันส่งข้อสอบให้หน่วยโสต" })).toHaveCount(0);
  await logout(); await login("review.print"); await page.goto(requestUrl);
  await page.getByRole("button", { name: "รับงานและเตรียมพิมพ์", exact: true }).click();
  await expect(page.getByRole("combobox", { name: "ไฟล์ที่ใช้พิมพ์" })).toContainText("workflow-v2.pdf", { timeout: 45_000 });
  await page.getByRole("button", { name: "ยืนยันไฟล์และจำนวนพิมพ์", exact: true }).click();
  await expect(page.getByRole("button", { name: "สร้างใบปะหน้าทุกห้อง" })).toBeEnabled();
  await page.getByRole("button", { name: "สร้างใบปะหน้าทุกห้อง" }).click();
  await expect(page.getByRole("button", { name: "เริ่มพิมพ์", exact: true })).toBeVisible({ timeout: 30_000 });
  await page.getByRole("button", { name: "แก้ไขไฟล์หรือจำนวน", exact: true }).click();
  await page.getByLabel("สำรอง", { exact: true }).first().fill("2");
  await page.getByRole("button", { name: "ยืนยันไฟล์และจำนวนพิมพ์", exact: true }).click();
  await expect(page.getByRole("button", { name: "เริ่มพิมพ์", exact: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "สร้างใบปะหน้าทุกห้อง", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "สร้างใบปะหน้าทุกห้อง" }).click();
  await expect(page.getByRole("button", { name: "เริ่มพิมพ์", exact: true })).toBeVisible({ timeout: 30_000 });
  const coverLink = (await page.locator('a[href*="/api/cover-sheets/"]').filter({ hasText: "v2" }).first().getAttribute("href"))!;
  const coverResponse = await page.request.get(coverLink); expect(coverResponse.ok()).toBe(true);
  await writeFile(info.outputPath("cover-sample.pdf"), await coverResponse.body());
  await page.screenshot({ path: info.outputPath("av-prepared.png"), fullPage: true });
  await page.getByRole("button", { name: "เริ่มพิมพ์", exact: true }).click();
  await expect(page.getByRole("button", { name: "ยืนยันไฟล์และจำนวนพิมพ์", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "ยืนยันพิมพ์เสร็จ", exact: true }).click();
  await expect(page.getByRole("heading", { name: "พิมพ์เสร็จแล้ว · จบงานในระบบ" })).toBeVisible({ timeout: 45_000 });
  await expect(page.getByTestId("current-task").getByRole("link")).toHaveCount(0);
  await expect(page.getByRole("button", { name: "สร้างใบปะหน้าทุกห้อง" })).toHaveCount(0);
  await expect(page.getByRole("heading", { name: "พิมพ์เสร็จแล้ว · จบงานในระบบ" })).toBeVisible();
  await expect(page.getByRole("button", { name: "ยืนยันส่งมอบ", exact: true })).toHaveCount(0);
  await expect(page.getByRole("link", { name: "รับมอบ/แจกจ่าย", exact: true })).toHaveCount(0);
  await page.screenshot({ path: info.outputPath("print-completed.png"), fullPage: true });
  await logout(); await login("review.officer"); await page.goto(requestUrl);
  await expect(page.getByRole("link", { name: "ดาวน์โหลด", exact: true })).toHaveCount(0);
  await expect(page.getByTestId("current-task").getByRole("link")).toHaveCount(0);
  await expect(page.getByRole("link", { name: "รับมอบ/แจกจ่าย", exact: true })).toHaveCount(0);
  expect((await page.request.post("/api/distributions/scan/00000000-0000-4000-8000-000000000000", { data: {} })).status()).toBe(404);
  expect(browserErrors).toEqual([]);
});
