import { expect, test, type Locator } from "@playwright/test";
import { PDFDocument } from "pdf-lib";
import { writeFile } from "node:fs/promises";

test("four roles: accounts → two rooms → form/PDF → rework → quantities/covers → print completion", async ({ page }, info) => {
  test.skip(!process.env.REVIEW_PASSWORD || info.project.name !== "chromium", "Requires isolated local workflow test accounts");
  test.setTimeout(300_000);
  const suffix = Date.now().toString().slice(-8);
  const course = `WF${suffix}`, round = `Workflow ${suffix}`, teacher = `teacher.${suffix}`;
  const teacherName = `อาจารย์ทดสอบ ${suffix}`, temporary = "InitialWorkflow2026!", personal = "PersonalWorkflow2026!";
  const browserErrors: string[] = [];
  page.on("pageerror", error => browserErrors.push(error.message));
  page.on("dialog", async dialog => { browserErrors.push("native dialog"); await dialog.dismiss(); });
  const logout = async () => {
    await page.getByRole("button", { name: "ออกจากระบบ", exact: true }).first().click();
    // Wait for sign-out and navigation before opening another account's login page.
    await expect(page).toHaveURL(/\/login$/);
  };
  const login = async (username: string, password = process.env.REVIEW_PASSWORD!, initial = false) => {
    await page.goto("/login");
    await page.getByLabel("Username", { exact: true }).fill(username);
    await page.getByLabel("รหัสผ่าน", { exact: true }).fill(password);
    for (let attempt = 0; attempt < 3; attempt++) {
      const response = page.waitForResponse(r => r.url().includes("/sign-in/username"));
      await page.getByRole("button", { name: "เข้าสู่ระบบ", exact: true }).click();
      if ((await response).status() !== 429) break;
      await page.waitForTimeout(11_000);
    }
    await expect(page).toHaveURL(initial ? /change-password/ : /\/dashboard$/);
    if (!initial) await expect(page.getByText("ขั้นตอนทั้งหมดของระบบ", { exact: true })).toHaveCount(0);
  };
  const checkButton = async (button: Locator, label: string) => {
    await expect(button).toBeVisible();
    for (const dark of [false, true]) {
      if ((await page.evaluate(() => document.documentElement.classList.contains("dark"))) !== dark) await page.getByRole("button", { name: "สลับโหมดสี", exact: true }).click();
      for (const width of [360, 768, 1024, 1440]) {
        await page.setViewportSize({ width, height: 1000 });
        const measure = await button.evaluate(element => {
          const canvas = document.createElement("canvas"); canvas.width = canvas.height = 1;
          const ctx = canvas.getContext("2d")!; ctx.fillStyle = "white"; ctx.fillRect(0, 0, 1, 1);
          const parents: Element[] = []; for (let node: Element | null = element; node; node = node.parentElement) parents.unshift(node);
          for (const node of parents) { ctx.fillStyle = getComputedStyle(node).backgroundColor; ctx.fillRect(0, 0, 1, 1); }
          const luminance = () => Array.from(ctx.getImageData(0, 0, 1, 1).data).slice(0, 3).reduce((sum, channel, index) => { const value = channel / 255; return sum + (value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4) * [0.2126, 0.7152, 0.0722][index]; }, 0);
          const background = luminance(); ctx.fillStyle = getComputedStyle(element).color; ctx.fillRect(0, 0, 1, 1); const foreground = luminance();
          return { height: element.getBoundingClientRect().height, contrast: (Math.max(background, foreground) + 0.05) / (Math.min(background, foreground) + 0.05), overflow: document.documentElement.scrollWidth > innerWidth + 1 };
        });
        expect(measure.height).toBeGreaterThanOrEqual(44); expect(measure.contrast).toBeGreaterThanOrEqual(4.5); expect(measure.overflow).toBe(false);
        await page.screenshot({ path: info.outputPath(`${label}-${dark ? "dark" : "light"}-${width}.png`), fullPage: true });
      }
    }
    if (await page.evaluate(() => document.documentElement.classList.contains("dark"))) await page.getByRole("button", { name: "สลับโหมดสี", exact: true }).click();
  };
  const choose = async (name: string, option: string | RegExp) => {
    await page.getByRole("combobox", { name, exact: true }).click();
    await page.getByRole("option", { name: option, exact: typeof option === "string" }).click();
  };
  const openForm = async (path: string, label: string, heading = label) => {
    await page.goto(path);
    await page.getByRole("link", { name: label, exact: true }).click();
    await expect(page.getByRole("heading", { name: heading, exact: true })).toBeVisible();
  };
  await login("review.admin");
  await page.goto("/dashboard/users");
  await page.getByLabel("Username", { exact: true }).fill(teacher);
  await page.getByLabel("ชื่อ-นามสกุล", { exact: true }).first().fill(teacherName);
  await page.getByLabel("อีเมล", { exact: true }).first().fill(`${teacher}@example.local`);
  await choose("บทบาท", "อาจารย์");
  await page.getByLabel("รหัสผ่านชั่วคราว", { exact: true }).fill(temporary);
  await page.getByRole("button", { name: "สร้างบัญชี", exact: true }).click();
  await expect(page.getByRole("cell").filter({ hasText: teacher }).first()).toBeVisible();
  const teacherRow = page.getByRole("row").filter({ hasText: teacher });
  await teacherRow.getByText("จัดการบัญชี", { exact: true }).click();
  await expect(teacherRow.locator("summary").filter({ hasText: "ตั้งรหัสผ่านชั่วคราว" })).toBeVisible();
  await logout();
  await login("review.officer");
  await openForm("/dashboard/rounds", "สร้างรอบสอบ");
  await choose("รอบสอบ", "รอบสอบอื่น");
  await page.getByLabel("ชื่อรอบสอบอื่น", { exact: true }).fill(round);
  await page.getByLabel("ปีการศึกษา").fill("2569"); await page.getByLabel("ภาคการศึกษา").fill("1");
  await page.getByRole("button", { name: "สร้างรอบสอบ", exact: true }).click();
  await expect(page.getByText("สร้างรอบสอบแล้ว", { exact: true })).toBeVisible();
  const roundRow = page.getByRole("row").filter({ has: page.getByRole("cell", { name: round, exact: true }) });
  await roundRow.getByRole("link", { name: "แก้ไขรอบสอบ", exact: true }).click();
  await expect(page.getByRole("heading", { name: "แก้ไขรอบสอบ", exact: true })).toBeVisible();
  await expect(page.getByLabel("ชื่อรอบสอบอื่น", { exact: true })).toHaveValue(round);
  await page.getByLabel("ภาคการศึกษา").fill("2");
  await page.getByLabel("เปิดรับต้นฉบับ", { exact: true }).fill("2026-09-01");
  await page.getByLabel("ปิดรับต้นฉบับ", { exact: true }).fill("2026-12-19");
  await page.getByRole("button", { name: "บันทึกแก้ไขรอบสอบ", exact: true }).click();
  await expect(roundRow).toContainText("2569 / 2");
  await openForm("/dashboard/rounds", "สร้างรอบสอบ");
  await choose("รอบสอบ", "รอบสอบอื่น");
  await page.getByLabel("ชื่อรอบสอบอื่น").fill(round + " DELETE");
  await page.getByLabel("ปีการศึกษา").fill("2569"); await page.getByLabel("ภาคการศึกษา").fill("1");
  await page.getByRole("button", { name: "สร้างรอบสอบ", exact: true }).click();
  const unusedRound = page.getByRole("row").filter({ hasText: round + " DELETE" });
  await unusedRound.getByRole("button", { name: "ลบ", exact: true }).click();
  await page.getByRole("button", { name: "กลับไปตรวจทาน", exact: true }).click();
  await expect(unusedRound).toBeVisible();
  await unusedRound.getByRole("button", { name: "ลบ", exact: true }).click();
  await page.getByRole("button", { name: "ยืนยันลบ", exact: true }).click();
  await expect(unusedRound).toHaveCount(0);
  for (const room of ["A", "B"]) {
    await openForm("/dashboard/rooms", "เพิ่มห้อง");
    await page.getByLabel("รหัสห้อง").fill(course + room);
    await page.getByLabel("ชื่อห้อง", { exact: true }).fill(`ห้องทดสอบ ${room}`);
    await page.getByLabel("ความจุ", { exact: true }).fill("50");
    await page.getByRole("button", { name: "เพิ่มห้องสอบ", exact: true }).click();
    await expect(page.getByRole("cell", { name: course + room, exact: true })).toBeVisible();
  }
  const roomRow = page.getByRole("row").filter({ has: page.getByRole("cell", { name: course + "A", exact: true }) });
  await roomRow.getByRole("link", { name: "แก้ไขห้อง", exact: true }).click();
  await expect(page.getByRole("heading", { name: "แก้ไขห้องสอบ", exact: true })).toBeVisible();
  await expect(page.getByLabel("ชื่อห้อง", { exact: true })).toHaveValue("ห้องทดสอบ A");
  await page.getByLabel("อาคาร", { exact: true }).fill("อาคารทดสอบ");
  await page.getByRole("button", { name: "บันทึกแก้ไขห้องสอบ", exact: true }).click();
  await expect(roomRow).toContainText("อาคารทดสอบ");
  await openForm("/dashboard/rooms", "เพิ่มห้อง");
  await page.getByLabel("รหัสห้อง").fill(course + "DELETE");
  await page.getByLabel("ชื่อห้อง", { exact: true }).fill("ห้องทดสอบลบ");
  await page.getByLabel("ความจุ", { exact: true }).fill("10");
  await page.getByRole("button", { name: "เพิ่มห้องสอบ", exact: true }).click();
  const unusedRoom = page.getByRole("row").filter({ hasText: course + "DELETE" });
  await unusedRoom.getByRole("button", { name: "ลบ", exact: true }).click();
  await page.getByRole("button", { name: "ยืนยันลบ", exact: true }).click();
  await expect(unusedRoom).toHaveCount(0);
  await openForm("/dashboard/subjects", "เพิ่มรายวิชา");
  await choose("รอบสอบ", new RegExp(round)); await choose("อาจารย์ผู้รับผิดชอบ", new RegExp(teacher));
  await page.getByLabel("รหัสวิชา", { exact: true }).fill(course);
  await page.getByLabel("ชื่อวิชา", { exact: true }).fill("การเขียนโปรแกรมและการจัดพิมพ์ข้อสอบสำหรับรายวิชาที่มีชื่อยาว");
  await page.getByRole("combobox", { name: "คณะ", exact: true }).click();
  await expect(page.getByRole("option")).toHaveCount(16);
  await page.getByRole("option", { name: "คณะวิศวกรรมศาสตร์", exact: true }).click();
  await page.getByLabel("กลุ่มเรียน").fill("1");
  await page.getByRole("button", { name: "เพิ่มรายวิชา", exact: true }).click();
  await expect(page.getByText("เพิ่มรายวิชาแล้ว", { exact: true })).toBeVisible();
  await page.getByRole("row").filter({ hasText: course }).getByRole("link", { name: "แก้ไขรายวิชา", exact: true }).click();
  await expect(page.getByRole("heading", { name: "แก้ไขรายวิชา", exact: true })).toBeVisible();
  await expect(page.getByRole("combobox", { name: "คณะ", exact: true })).toContainText("คณะวิศวกรรมศาสตร์");
  await page.getByLabel("กลุ่มเรียน").fill("2");
  await page.getByRole("button", { name: "บันทึกแก้ไขรายวิชา", exact: true }).click();
  await expect(page.getByRole("row").filter({ hasText: course }).getByRole("cell", { name: "2", exact: true })).toBeVisible();
  for (const room of ["A", "B"]) {
    await openForm("/dashboard/subjects", "จัดตารางสอบ");
    await choose("รายวิชา", new RegExp(course)); await choose("ห้องสอบ", new RegExp(course + room));
    await page.getByLabel("วันที่สอบ").fill("2026-09-20");
    await page.getByLabel("เริ่ม", { exact: true }).fill("09:00"); await page.getByLabel("สิ้นสุด", { exact: true }).fill("11:00");
    await expect(page.getByLabel("ผู้เข้าสอบห้องนี้")).toHaveCount(0);
    await page.getByRole("button", { name: "บันทึกตารางสอบ", exact: true }).click();
    await expect(page.getByText("บันทึกตารางสอบแล้ว", { exact: true })).toBeVisible();
  }
  const scheduleRow = page.getByRole("row").filter({ hasText: course + "B" });
  await scheduleRow.getByRole("link", { name: "แก้ไขตาราง", exact: true }).click();
  await expect(page.getByRole("heading", { name: "แก้ไขตารางสอบ", exact: true })).toBeVisible();
  await page.getByLabel("สิ้นสุด", { exact: true }).fill("12:00");
  await page.getByRole("button", { name: "บันทึกตารางสอบ", exact: true }).click();
  await expect(scheduleRow).toContainText("12:00");
  await scheduleRow.getByRole("button", { name: "ลบ", exact: true }).click();
  await page.getByRole("button", { name: "ยืนยันลบ", exact: true }).click();
  await expect(scheduleRow).toHaveCount(0);
  await openForm("/dashboard/subjects", "จัดตารางสอบ");
  await choose("รายวิชา", new RegExp(course)); await choose("ห้องสอบ", new RegExp(course + "B"));
  await page.getByLabel("วันที่สอบ").fill("2026-09-20");
  await page.getByLabel("เริ่ม", { exact: true }).fill("09:00"); await page.getByLabel("สิ้นสุด", { exact: true }).fill("11:00");
  await page.getByRole("button", { name: "บันทึกตารางสอบ", exact: true }).click();
  await expect(page.getByText("บันทึกตารางสอบแล้ว", { exact: true })).toBeVisible();
  await logout(); await login(teacher, temporary, true);
  await page.getByLabel("รหัสผ่านชั่วคราว", { exact: true }).fill(temporary);
  await page.getByLabel("รหัสผ่านใหม่", { exact: true }).fill(personal);
  await page.getByLabel("ยืนยันรหัสผ่านใหม่", { exact: true }).fill(personal);
  await page.getByRole("button", { name: "บันทึกรหัสผ่านใหม่", exact: true }).click();
  await expect(page).toHaveURL(/\/dashboard$/);
  await page.goto("/dashboard/requests/new");
  await choose("รายวิชาของคุณ", new RegExp(course));
  await page.getByRole("button", { name: "ถัดไป: กรอกแบบฟอร์ม", exact: true }).click();
  await page.getByLabel("สาขาวิชา", { exact: true }).fill("วิทยาการคอมพิวเตอร์");
  await choose("ภาษาข้อสอบ", "ไทย"); await choose("รูปแบบพิมพ์", "สองหน้า");
  await choose("กระดาษคำตอบคอมพิวเตอร์", "ไม่ต้องการ"); await choose("ประเภทการสอบ", "ในตาราง");
  await page.getByLabel("เบอร์ผู้ประสานงาน").fill("0812345678");
  await page.getByRole("checkbox", { name: "นำเครื่องคิดเลขเข้าห้องสอบได้", exact: true }).check();
  await page.getByLabel("คำอธิบายเพิ่มเติมผู้ส่งข้อสอบ").fill("ตรวจจำนวนข้อสอบให้ครบก่อนเริ่มสอบ และแจ้งผู้คุมสอบเมื่อพบข้อผิดพลาด");
  await page.getByLabel("จำนวนชุดข้อสอบที่ขอ", { exact: true }).nth(0).fill("10001");
  await expect(page.getByRole("alert").filter({ hasText: "ห้องนี้รองรับ 50 คน" })).toBeVisible();
  await page.getByRole("button", { name: "บันทึกฉบับร่าง", exact: true }).click();
  await expect(page.getByText("กรุณาแก้ไขจำนวนในช่องที่มีข้อความเตือนด้านล่าง", { exact: true })).toBeVisible();
  await expect(page.getByLabel("สาขาวิชา", { exact: true })).toHaveValue("วิทยาการคอมพิวเตอร์");
  await expect(page.getByText(/too_big|expected number|"origin"/)).toHaveCount(0);
  await page.getByLabel("จำนวนชุดข้อสอบที่ขอ", { exact: true }).nth(0).fill("50");
  await page.getByLabel("จำนวนชุดข้อสอบที่ขอ", { exact: true }).nth(1).fill("30");
  const pdf = await PDFDocument.create(); pdf.addPage().drawText("Workflow fixture - not a real examination");
  const buffer = Buffer.from(await pdf.save());
  await page.getByLabel("ไฟล์ข้อสอบ PDF (สูงสุด 100 MB)", { exact: true }).setInputFiles({ name: "workflow-v1.pdf", mimeType: "application/pdf", buffer });
  for (const width of [360, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 1000 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
    await page.screenshot({ path: info.outputPath(`teacher-form-${width}.png`), fullPage: true });
  }
  await page.getByRole("button", { name: "ถัดไป: ตรวจทาน", exact: true }).click();
  await expect(page.getByRole("button", { name: "ยืนยันส่งข้อสอบให้หน่วยโสต" })).toBeVisible({ timeout: 30_000 });
  await page.getByRole("button", { name: "ยืนยันส่งข้อสอบให้หน่วยโสต" }).click();
  await expect(page).toHaveURL(/\/requests\/[a-f0-9-]+$/);
  const requestUrl = page.url();
  const cancel = page.getByRole("button", { name: "ยกเลิกคำขอ", exact: true });
  await checkButton(cancel, "cancel-visible");
  await cancel.click(); await expect(page.getByRole("alertdialog")).toBeVisible();
  await page.getByRole("button", { name: "กลับไปตรวจทาน", exact: true }).click();
  await logout(); await login("review.print"); await page.goto(requestUrl);
  const fileLink = page.getByTestId("current-task").getByRole("link", { name: /workflow-v1.pdf/ });
  const fileResponse = await page.request.get((await fileLink.getAttribute("href"))!);
  expect(fileResponse.ok()).toBe(true);
  await expect(page.getByRole("button", { name: "ส่งกลับให้อาจารย์แก้ไข", exact: true })).toBeVisible();
  await checkButton(page.getByRole("button", { name: "ส่งกลับให้อาจารย์แก้ไข", exact: true }), "return-visible");
  await page.getByLabel("เหตุผลที่ส่งกลับ").fill("กรุณาตรวจข้อความคำแนะนำอีกครั้ง");
  await page.getByRole("button", { name: "ส่งกลับให้อาจารย์แก้ไข" }).click();
  await expect(page.getByText("ปฏิเสธ/ส่งกลับแก้ไข", { exact: true }).first()).toBeVisible();
  await logout(); await login(teacher, personal); await page.goto(requestUrl);
  await expect(page.getByLabel("ไฟล์ข้อสอบ PDF (สูงสุด 100 MB)", { exact: true })).toBeEnabled();
  await page.getByLabel("ไฟล์ข้อสอบ PDF (สูงสุด 100 MB)", { exact: true }).setInputFiles({ name: "workflow-v2.pdf", mimeType: "application/pdf", buffer });
  await expect(page.getByText("ไฟล์ที่เลือก: workflow-v2.pdf", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "ถัดไป: ตรวจทาน", exact: true }).click();
  await expect(page.getByText(/ข้อสอบ .*workflow-v2\.pdf/)).toBeVisible({ timeout: 30_000 });
  await page.getByRole("button", { name: "ยืนยันส่งข้อสอบให้หน่วยโสต" }).click();
  // The submit button changes to a pending label immediately; wait for actual completion.
  await expect(page.getByRole("button", { name: "กำลังส่ง...", exact: true })).toHaveCount(0, { timeout: 45_000 });
  await expect(page.getByRole("button", { name: "ยืนยันส่งข้อสอบให้หน่วยโสต" })).toHaveCount(0);
  const liveContext = await page.context().browser()!.newContext({ baseURL: new URL(page.url()).origin });
  const liveTeacher = await liveContext.newPage();
  await liveTeacher.goto("/login");
  await liveTeacher.getByLabel("Username", { exact: true }).fill(teacher);
  await liveTeacher.getByLabel("รหัสผ่าน", { exact: true }).fill(personal);
  await liveTeacher.getByRole("button", { name: "เข้าสู่ระบบ", exact: true }).click();
  await expect(liveTeacher).toHaveURL(/\/dashboard$/);
  await expect(liveTeacher.getByText("เหตุผล: กรุณาตรวจข้อความคำแนะนำอีกครั้ง", { exact: true })).toBeVisible();
  await expect(liveTeacher.getByText("ข้อสอบของคุณมีการอัปเดต", { exact: true })).toHaveCount(0);
  await logout(); await login("review.print"); await page.goto(requestUrl);
  await page.getByRole("button", { name: "รับงานและเตรียมพิมพ์", exact: true }).click();
  await expect(page.getByRole("combobox", { name: "ไฟล์ที่ใช้พิมพ์" })).toContainText("workflow-v2.pdf", { timeout: 45_000 });
  // A live teacher tab updates through its one polling loop, not a page refresh.
  await expect(liveTeacher.getByText("ข้อสอบของคุณมีการอัปเดต", { exact: true })).toBeVisible({ timeout: 35_000 });
  await expect(liveTeacher.getByText("หน่วยโสตรับงานแล้วและกำลังเตรียมพิมพ์", { exact: true })).toBeVisible();
  await liveContext.close();
  await page.getByRole("button", { name: "ยืนยันไฟล์และจำนวนพิมพ์", exact: true }).click();
  await expect(page.getByRole("button", { name: "สร้างใบปะหน้าทุกห้อง" })).toBeEnabled();
  await page.getByRole("button", { name: "สร้างใบปะหน้าทุกห้อง" }).click();
  await expect(page.getByRole("button", { name: "เริ่มพิมพ์", exact: true })).toBeVisible({ timeout: 30_000 });
  const oldCoverHref = (await page.locator('a[href*="/api/cover-sheets/"]').filter({ hasText: "v1" }).first().getAttribute("href"))!;
  const oldPdf = await page.request.get(oldCoverHref); expect(oldPdf.ok()).toBe(true);
  await writeFile(info.outputPath("cover-before-rename.pdf"), await oldPdf.body());
  await logout(); await login(teacher, personal);
  const updateRegion = page.getByRole("region", { name: "การอัปเดตข้อสอบล่าสุด", exact: true });
  await expect(updateRegion.getByRole("link")).toHaveCount(2);
  const feedResponse = await page.request.get("/api/notifications?userId=someone-else");
  expect(feedResponse.headers()["cache-control"]).toBe("no-store");
  const feed = (await feedResponse.json()).notifications;
  expect(feed.filter((row: { requestId: string }) => requestUrl.endsWith(row.requestId))).toHaveLength(2);
  expect(feed.every((row: object) => !("emailTo" in row) && !("lastError" in row))).toBe(true);
  for (const dark of [false, true]) {
    if ((await page.evaluate(() => document.documentElement.classList.contains("dark"))) !== dark) await page.getByRole("button", { name: "สลับโหมดสี", exact: true }).click();
    for (const width of [360, 768, 1024, 1440]) {
      await page.setViewportSize({ width, height: 1000 });
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
      await page.screenshot({ path: info.outputPath(`teacher-notifications-${dark ? "dark" : "light"}-${width}.png`), fullPage: true });
      await page.getByRole("button", { name: "การแจ้งเตือนข้อสอบ", exact: true }).click();
      const sheet = page.getByRole("dialog", { name: "การแจ้งเตือนข้อสอบ", exact: true });
      await expect(sheet.getByRole("link")).toHaveCount(2);
      await expect(sheet).toContainText("กรุณาตรวจข้อความคำแนะนำอีกครั้ง");
      expect(await sheet.evaluate(element => element.getBoundingClientRect().width <= innerWidth)).toBe(true);
      await page.screenshot({ path: info.outputPath(`notification-sheet-${dark ? "dark" : "light"}-${width}.png`) });
      await page.keyboard.press("Escape");
      await expect(sheet).toHaveCount(0);
    }
  }
  await updateRegion.getByRole("link").first().click(); await expect(page).toHaveURL(requestUrl);
  await logout(); await login("review.admin"); await page.goto("/dashboard/notifications");
  await expect(page.getByText(/^SMTP · Mailpit/)).toBeVisible();
  const mailTest = page.waitForResponse(response => response.request().method() === "POST" && response.url().includes("/dashboard/notifications"));
  await page.getByRole("button", { name: "ส่งเมลทดสอบ", exact: true }).click();
  expect((await mailTest).ok()).toBe(true);
  await expect(page.getByText(/เซิร์ฟเวอร์ยอมรับอีเมลทดสอบแล้ว/).first()).toBeVisible();
  await page.goto("/dashboard/users");
  await teacherRow.getByText("จัดการบัญชี", { exact: true }).click();
  await expect(teacherRow.getByText("ตั้งรหัสผ่านชั่วคราว", { exact: true })).toHaveCount(0);
  await teacherRow.getByText("แก้รหัสผ่าน", { exact: true }).click();
  await expect(teacherRow.getByLabel("รหัสผ่านใหม่", { exact: true })).toHaveValue("");
  await teacherRow.getByText("แก้ไขข้อมูลและบทบาท", { exact: true }).click();
  await teacherRow.getByLabel("ชื่อ-นามสกุล", { exact: true }).fill(teacherName + " แก้ชื่อแล้ว");
  await teacherRow.getByRole("button", { name: "บันทึกข้อมูล", exact: true }).click();
  await expect(teacherRow).toContainText(teacherName + " แก้ชื่อแล้ว");
  await logout(); await login("review.print"); await page.goto(requestUrl);
  const editPlan = page.getByRole("button", { name: "แก้ไขไฟล์หรือจำนวน", exact: true });
  await expect(editPlan).toHaveAttribute("data-variant", "outline");
  await checkButton(editPlan, "edit-plan-visible");
  await page.getByRole("button", { name: "แก้ไขไฟล์หรือจำนวน", exact: true }).click();
  await page.getByLabel("สำรอง", { exact: true }).first().fill("2");
  await page.getByRole("button", { name: "ยืนยันไฟล์และจำนวนพิมพ์", exact: true }).click();
  await expect(page.getByRole("button", { name: "เริ่มพิมพ์", exact: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "สร้างใบปะหน้าทุกห้อง", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "สร้างใบปะหน้าทุกห้อง" }).click();
  await expect(page.getByRole("button", { name: "เริ่มพิมพ์", exact: true })).toBeVisible({ timeout: 30_000 });
  const coverLink = (await page.locator('a[href*="/api/cover-sheets/"]').filter({ hasText: "v2" }).first().getAttribute("href"))!;
  const coverResponse = await page.request.get(coverLink); expect(coverResponse.ok()).toBe(true);
  await writeFile(info.outputPath("cover-sample.pdf"), await coverResponse.body());
  await page.screenshot({ path: info.outputPath("av-prepared.png"), fullPage: true });
  await page.getByRole("button", { name: "เริ่มพิมพ์", exact: true }).click();
  await expect(page.getByRole("button", { name: "ยืนยันไฟล์และจำนวนพิมพ์", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "ยืนยันพิมพ์เสร็จ", exact: true }).click();
  await expect(page.getByRole("heading", { name: "พิมพ์เสร็จแล้ว · จบงานในระบบ" })).toBeVisible({ timeout: 45_000 });
  await expect(page.getByTestId("current-task").getByRole("link")).toHaveCount(0);
  await expect(page.getByRole("button", { name: "สร้างใบปะหน้าทุกห้อง" })).toHaveCount(0);
  await expect(page.getByRole("heading", { name: "พิมพ์เสร็จแล้ว · จบงานในระบบ" })).toBeVisible();
  await expect(page.getByRole("button", { name: "ยืนยันส่งมอบ", exact: true })).toHaveCount(0);
  await expect(page.getByRole("link", { name: "รับมอบ/แจกจ่าย", exact: true })).toHaveCount(0);
  await page.screenshot({ path: info.outputPath("print-completed.png"), fullPage: true });
  await logout(); await login("review.officer"); await page.goto(requestUrl);
  await expect(page.getByRole("link", { name: "ดาวน์โหลด", exact: true })).toHaveCount(0);
  await expect(page.getByTestId("current-task").getByRole("link")).toHaveCount(0);
  await expect(page.getByRole("link", { name: "รับมอบ/แจกจ่าย", exact: true })).toHaveCount(0);
  expect((await page.request.post("/api/distributions/scan/00000000-0000-4000-8000-000000000000", { data: {} })).status()).toBe(404);
  await page.goto("/dashboard/rounds");
  await expect(roundRow.getByRole("link", { name: "แก้ไขรอบสอบ", exact: true })).toHaveCount(0);
  await roundRow.getByRole("button", { name: /เหตุผลที่ล็อก/ }).click();
  await expect(page.getByRole("alertdialog")).toContainText("ประวัติคำขอ");
  await expect(page.getByRole("button", { name: "ยืนยันลบ", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "เข้าใจแล้ว", exact: true }).click();
  for (const path of ["rounds", "rooms", "subjects"]) {
    await page.goto(`/dashboard/${path}`);
    for (const width of [360, 768, 1024, 1440]) {
      await page.setViewportSize({ width, height: 1000 });
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
      await page.screenshot({ path: info.outputPath(`setup-${path}-${width}.png`), fullPage: true });
    }
  }
  await page.goto("/dashboard/rooms");
  await roomRow.getByRole("button", { name: /เหตุผลที่ลบไม่ได้/ }).click();
  await expect(page.getByRole("alertdialog")).toContainText("ต้องลบตาราง");
  await page.getByRole("button", { name: "เข้าใจแล้ว", exact: true }).click();
  await roomRow.getByRole("link", { name: "แก้ไขห้อง", exact: true }).focus();
  await page.keyboard.press("Enter");
  await expect(page.getByRole("heading", { name: "แก้ไขห้องสอบ", exact: true })).toBeVisible();
  await logout(); await login(teacher, personal);
  await expect(page.getByRole("region", { name: "การอัปเดตข้อสอบล่าสุด", exact: true }).getByRole("link")).toHaveCount(3);
  const finalEvents = (await (await page.request.get("/api/notifications")).json()).notifications;
  expect(finalEvents.filter((row: { requestId: string }) => requestUrl.endsWith(row.requestId))).toHaveLength(4);
  await page.screenshot({ path: info.outputPath("teacher-all-events-complete.png"), fullPage: true });
  await logout(); await login("review.admin"); await page.goto("/dashboard/users");
  await teacherRow.getByText("จัดการบัญชี", { exact: true }).click();
  await teacherRow.getByText("แก้รหัสผ่าน", { exact: true }).click();
  const replacement = "ReplacedWorkflow2026!";
  await teacherRow.getByLabel("รหัสผ่านใหม่", { exact: true }).fill(replacement);
  await teacherRow.getByRole("button", { name: "บันทึกรหัสผ่านใหม่", exact: true }).click();
  await expect(teacherRow.locator("summary").filter({ hasText: "ตั้งรหัสผ่านชั่วคราว" })).toBeVisible();
  await logout(); await login(teacher, replacement, true);
  await expect(page.getByRole("heading", { name: "ตั้งรหัสผ่านส่วนตัว", exact: true })).toBeVisible();
  expect(browserErrors).toEqual([]);
});
